[workspace]
authors = ["Szil√°gyi Csaba <csabi32105@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
name = "horzie"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.3.4,<3"
pandas = ">=2.3.3,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.7,<4"
scikit-learn = ">=1.7.2,<2"
ipython = ">=9.7.0,<10"
jupyterlab = ">=4.4.10,<5"
pytorch = "2.4.*"
torchvision = "0.19.*"
torchaudio = "2.4.*"
pytorch-cuda = "12.*"
